// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXgqFh_4Zd_O9XLzEKJ33VOnZBvohhmPQ',
    appId: '1:824091918512:web:e6aa1b016bf84942267b75',
    messagingSenderId: '824091918512',
    projectId: 'pasca-ios-and-android-dc988',
    authDomain: 'pasca-ios-and-android-dc988.firebaseapp.com',
    storageBucket: 'pasca-ios-and-android-dc988.appspot.com',
    measurementId: 'G-BFNGP62QWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNrlzSWnwRenT89arxDEqv4bhNf-Le3JA',
    appId: '1:824091918512:android:cff2cd79d8e0ac98267b75',
    messagingSenderId: '824091918512',
    projectId: 'pasca-ios-and-android-dc988',
    storageBucket: 'pasca-ios-and-android-dc988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL8gqF8DVeVhBguAfqJB4UGi51mFxTvMw',
    appId: '1:824091918512:ios:4ace7276b85a73aa267b75',
    messagingSenderId: '824091918512',
    projectId: 'pasca-ios-and-android-dc988',
    storageBucket: 'pasca-ios-and-android-dc988.appspot.com',
    iosBundleId: 'com.example.pasca',
  );
}
